DELETE FROM rpg_test.charactersstatistics;
DELETE FROM rpg_test.charactersinventory;
DELETE FROM rpg_test.charactershonor;
DELETE FROM rpg_test.charactersequipements;
DELETE FROM rpg_test.characterscraftlevel;
DELETE FROM rpg_test.charactersattacks;
DELETE FROM rpg_test.charactersachievements
DELETE FROM rpg_test.levels;
DELETE FROM rpg_test.statscharacters
DELETE FROM rpg_test.userspreferences;
DELETE FROM rpg_test.users;
DELETE FROM rpg_test.guildsmembers;
DELETE FROM rpg_test.conquesttournamentinscriptions;
DELETE FROM rpg_test.conquesttournamentrounds;
DELETE FROM rpg_test.guilds;
DELETE FROM rpg_test.`characters`;